name: kubeconform

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: docker-build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: docker-build
        run: |
          docker build .
