name: build

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: test
      run: make docker-test

    - name: build
      run: make docker-build-static