name: build

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: tests
      run: make docker-test

    - name: build
      run: make docker-build-static

    - name: acceptance-tests
      run:
        docker build -t bats -f Dockerfile.bats .
